### ISSUE TITLE
Get error Invalid redirect_url after clicking deep link 

### ISSUE THREAD

**Issue by Chengze-Wu** [dmitry-viskov/pylti1.3-flask-example#28]
Hi,

I followed the steps from [Using the pyLTI1p3 Library with Learn](https://docs.anthology.com/docs/lti/tutorials/pylti13) to learn how LTI 1.3 works.

Everything went well until we got this error.

![image](https://github.com/dmitry-viskov/pylti1.3-flask-example/assets/66125834/39474d6f-213e-4ade-997a-7979cd1e460b)
We have the deep link deployed successfully, but it throws this error when I click on the link.
![image](https://github.com/dmitry-viskov/pylti1.3-flask-example/assets/66125834/bee3c5e8-7254-4729-9edb-84c891952d57)

Does anyone get this issue?

Thanks!
Travis

**Comment by besonn** [comment]
The same error happened to me. I tried to run deep link in Moodle but failed. Did you fix this error? @Chengze-Wu

**Comment by Chengze-Wu** [comment]
> The same error happened to me. I tried to run deep link in Moodle but failed. Did you fix this error? @Chengze-Wu

Yes, I did fix it.
` 
resource.set_url(launch_url + '?difficulty=' + difficulty) \
        .set_custom_params({'difficulty': difficulty}) \
        .set_title('Breakout ' + difficulty + ' mode!')
`
should be
`
resource.set_url(launch_url) \
        .set_custom_params({'difficulty': difficulty}) \
        .set_title('Breakout ' + difficulty + ' mode!')
`

**Comment by besonn** [comment]
> > The same error happened to me. I tried to run deep link in Moodle but failed. Did you fix this error? @Chengze-Wu
> 
> Yes, I did fix it. ` resource.set_url(launch_url + '?difficulty=' + difficulty) \ .set_custom_params({'difficulty': difficulty}) \ .set_title('Breakout ' + difficulty + ' mode!')` should be `resource.set_url(launch_url) \ .set_custom_params({'difficulty': difficulty}) \ .set_title('Breakout ' + difficulty + ' mode!')`

@Chengze-Wu Thank you so much! I have solved this!
